### ISSUE TITLE
Some users that use Google oAuth with Plex can not login. 

### ISSUE THREAD

**Issue by TiddlyQwert** [petio-team/petio#242]
After first setting it up two users were able to login ( they also use Plex with Google oAuth). Once I had more users test they get user not found error when trying to login. In the console I am getting warnings saying "Failed Plex Auth". Had the original user test again after others started having issues and they still can login fine.

**Comment by TiddlyQwert** [comment]
Still working with my users. 

Things to note: 

Emails are case sensitive so have them check what Plex has it listed as. 

One user I sent the link via Facebook messenger and when they open it in messenger and not the browser app it will show failed login no matter the account and console will show failed plex auth. 

Still checking with the others who can't login and trying to narrow down the issue but I am starting to think it's because they don't know the case of the email or username they use. 

Will keep following up till they can login.

**Comment by AshDyson** [comment]
If possible can you dig through Petio db to find one of these google users and see what their user looks like?

This should be fairly easy to fix with a login with Plex button but I'd like to explore it more as I don't have any users using google auth

**Comment by AshDyson** [comment]
oAuth is now added in the upcoming patch, re-open this issue if this does not resolve google auth
