### ISSUE TITLE
Music/lidarr Integration

### ISSUE THREAD

**Issue by Hossy** [petio-team/petio#248]
**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
Support music requests using lidarr.

**Describe alternatives you've considered**
Ombi (what I use now)

**Comment by RyleaStark** [comment]
This integration is already on our roadmap!

**Comment by angrycuban13** [comment]
Since we have this on our roadmap we'll go ahead and close this feature request.
