### ISSUE TITLE
Allow TV Season/Episode Requests Instead of Entire Show

### ISSUE THREAD

**Issue by Hossy** [petio-team/petio#249]
**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
I would like to have the ability for users to request a specific season/episode (or "latest" season/episode) of a show instead of just the entire show with all seasons/episodes.

I would also like to see restrictions available in the user profiles to limit the number of seasons/episodes a user may request.

**Describe alternatives you've considered**
Ombi (what I use now)

**Comment by angrycuban13** [comment]
This is already part of our roadmap but wasn't planned for initial release. Thanks for your feature request!
