### ISSUE TITLE
Branding/Customization

### ISSUE THREAD

**Issue by Hossy** [petio-team/petio#251]
**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
I would like to add my own Plex graphics and text to the user side web UI -- like a landing page with the options for pre-login and post-login.  Things like my Plex logo, a message from me, some FAQs, ko-fi.com link, and maybe news about upcoming maintenance.

**Describe alternatives you've considered**
Ombi (what I use now)

**Comment by RyleaStark** [comment]
You could easily accomplish this by adding your own CSS file to override the already-defined styles, thus replacing the Petio branding. However it would be limited to using NGINX to proxy/stub your endpoint. Similar to how theme.park is applied to customize plex and other apps: https://github.com/gilbN/theme.park

**Comment by AshDyson** [comment]
Support for this is planned, although low priority for now. Will be implemented soon though
