### ISSUE TITLE
Movie Poster Blocks Part of Trailer

### ISSUE THREAD

**Issue by Hossy** [petio-team/petio#254]
**Describe the bug**
When playing a trailer, the post poster moves to the side, but still appears over the playing video.

**To Reproduce**
1. Play a trailer.

**Expected behavior**
The trailer should be the foreground.

**Screenshots**
![image](https://user-images.githubusercontent.com/1756846/111847349-a0f93e80-88d6-11eb-8ac2-1c792a7c95b3.png)

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser: Chrome
 - Version: 88.0.4324.190

**Comment by AshDyson** [comment]
Yeah this isn't an issue it's literally taking up at most like 30px

**Comment by Hossy** [comment]
> Yeah this isn't an issue it's literally taking up at most like 30px

50 pixels, actually.  Why do you want to cover up any portion of the trailer?  What purpose does it serve?
