### ISSUE TITLE
Can't Control Playback of Trailer

### ISSUE THREAD

**Issue by Hossy** [petio-team/petio#255]
**Describe the bug**
When playing a trailer, the pause/play/rewind/fast-forward/slider are all missing.  Fullscreen is also missing.

**To Reproduce**
1. Play a trailer.

**Expected behavior**
The playback controls should be visible.  I should have the option to go fullscreen as well.

**Screenshots**
![image](https://user-images.githubusercontent.com/1756846/111847477-e0278f80-88d6-11eb-82d9-e5104c566e6a.png)

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser: Chrome
 - Version: 88.0.4324.190

**Comment by AshDyson** [comment]
Not a bug intentional choice, video auto plays and auto pauses on close

**Comment by Hossy** [comment]
> Not a bug intentional choice, video auto plays and auto pauses on close

Can this be a feature request then?  Every other system allows full playback control of a trailer.  To me, this makes the trailer function unusable.  I have to constant Google for the trailer for something I'm browsing on Petio all because 50px are covered up and I can't control playback.
