### ISSUE TITLE
Login with plex.tv

### ISSUE THREAD

**Issue by Hossy** [petio-team/petio#257]
**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
I would like to users to be able to login with plex.tv authentication instead of digging out their randomly-generated 100-character passwords from their favorite password manager. :-)

**Describe alternatives you've considered**
Ombi (what I use now)

**Comment by PotentialIngenuity** [comment]
Plex Oauth is a planned feature

**Comment by angrycuban13** [comment]
You can meanwhile enable `Fast Login` under Settings and user will only need to use their username or email to log in.

**Comment by Hossy** [comment]
> You can meanwhile enable `Fast Login` under Settings and user will only need to use their username or email to log in.

I thought about that, but then anyone could hit it guessing an email.  Not like it's protecting anything super secure, but a user could just put in the admin email and then have all their requests auto-approved.

**Comment by angrycuban13** [comment]
True. This is the part where I sould say to look at something like Authelia or Organizr for auth in front of services like these

**Comment by AshDyson** [comment]
Planned and will be added
