### ISSUE TITLE
Don't Store Passwords in Plaintext

### ISSUE THREAD

**Issue by brettpetch** [petio-team/petio#258]
**Is your feature request related to a problem? Please describe.**
Passwords to the admin account are currently stored in plaintext at ``/opt/Petio/bin/config/config.json``. If this could be fixed, it'd be great.

**Describe the solution you'd like**
Passwords salted and hashed.

**Describe alternatives you've considered**
encrypting the config with ansible

**Additional context**
NA

**Comment by Motophan** [comment]
+1

**Comment by AshDyson** [comment]
Yeah this is planned. Currently only exposed for debugging purposes in first release. Will be patched
