### ISSUE TITLE
Guide Calendar Not Showing Movies

### ISSUE THREAD

**Issue by Hossy** [petio-team/petio#259]
**Describe the bug**
Upcoming movies aren't showing in the Guide calendar on the Requests page (user mode).  In this example, Godzilla vs. Kong.

The Status shows "-5d" although tmdb says the release date is 3/31/2021 -- #260.

**To Reproduce**
1. Put in a request for an upcoming movie.

**Expected behavior**
The description of the Guide says that it shows upcoming TV and movies, so I would expect to see the upcoming movie on the calendar.

**Screenshots**
![image](https://user-images.githubusercontent.com/1756846/111851758-8927b780-88e2-11eb-8639-8e0575fa0afc.png)

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser: Chrome
 - Version: 88.0.4324.190

**Comment by AshDyson** [comment]
Fix coming in next patch
