### ISSUE TITLE
Movie In Radarr, but not in Plex Allows Petio User to Request and Shows Pending Approval

### ISSUE THREAD

**Issue by Hossy** [petio-team/petio#261]
**Describe the bug**
When a user searches for a movie that is not in Plex, but already added to Radarr, the user is shown the movie has not been requested.  Initially, I would be okay with this because then they could add onto the request and be notified when the movie is added.  But, after they make the request, Petio shows the request as pending approval.

**To Reproduce**
1. Put in a request for a movie already in Radarr.

**Expected behavior**
The Pending status is invalid as Radarr is already tracking it.  Pending should be skipped for items already in Radarr/Sonarr.

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser: Chrome
 - Version: 88.0.4324.190

**Comment by angrycuban13** [comment]
This is expected behavior. Petio will not retroactively know what is in Sonarr/Radarr.

**Comment by Hossy** [comment]
> This is expected behavior. Petio will not retroactively know what is in Sonarr/Radarr.

Just to be clear, what I'm describing here is not that Petio should already know what Radarr is tracking.

The problem is that Petio is marking the request as PENDING even though Radarr is already searching for it (which would be the state if the item was approved).  There is no reason to ask an admin to approve a request for something already in Radarr/Sonarr.

**Comment by Hossy** [comment]
Also, to that end, this request should the not count against the user's quota
