### ISSUE TITLE
Easier Admin Request Decisions

### ISSUE THREAD

**Issue by Hossy** [petio-team/petio#262]
**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
I would like a couple things added to the Requests admin page:

* movie/show posters
* clickable links to open up the Petio movie/show page to read more about the item being requested
* After clicking edit, the default profile/location should be pre-selected for Radarr/Sonarr
* one-click approve button (next to Edit) that will always use the default profile/location
* one-click deny button (next to Edit)

**Describe alternatives you've considered**
Ombi (what I use now)

**Comment by AshDyson** [comment]
I agree with the link to movie data, and the default profile being used, the one click approve deny isn't something I want to include at this time.

**Comment by AshDyson** [comment]
Partially addressed in upcoming patch

Movie / show posters (only on dashboard not on request table)
Links from table item name and dashboard request card now link to media
Default profile / filter now applied as default on request edit
One clicks, not included, I can see the benefit but for now they're not included. May revisit this later, just adds some complexity for a quick shortcut
