### ISSUE TITLE
Recently Viewed Movies By You shows items not in library

### ISSUE THREAD

**Issue by ctrlaltd1337ed** [petio-team/petio#264]
**Describe the bug**
When looking at media listed in this section, it is showing movies that are not in my library. 

**To Reproduce**
1. Go to profile and look at items listed as recently viewed.
2. Click on a movie.
3. Click Watch Now.
4. Get linked to an incorrect video.

**Expected behavior**
Media not in my library should not be listed.

**Screenshots**
![image](https://user-images.githubusercontent.com/10511491/111858685-2699e000-8911-11eb-98f2-e81127abc69c.png)
^ All but Lethal Weapon 2 are not in my library.
![image](https://user-images.githubusercontent.com/10511491/111858688-2bf72a80-8911-11eb-8603-12e4e6e7c081.png)
![image](https://user-images.githubusercontent.com/10511491/111858691-331e3880-8911-11eb-8eeb-bca4622db130.png)
^ When clicking on "Watch Now" I am brought here.

**Desktop (please complete the following information):**
 - OS: Unraid 6.9.1
 - Browser: Chrome 89.0.4389.90
 - Version: 0.4.2-alpha

**Additional context**
Every incorrect match is linking to an "Other Videos" library I have for audio/video tests using Plex Video Files Scanner.
![image](https://user-images.githubusercontent.com/10511491/111858769-d3745d00-8911-11eb-96e8-be46fd1c9ce3.png)

**Comment by AshDyson** [comment]
Can you provide the xml data for this false match in Plex? Then we can identify what is causing it to incorrectly match.

**Comment by ctrlaltd1337ed** [comment]
Here you go: 

https://gist.github.com/ctrlaltd1337ed/e2258e54ba8bd315cef2ebac86f53e05

**Comment by AshDyson** [comment]
Fix coming in new patch, once the patch is released you'll need to delete the "movies" collection in mongo or if you'd prefer just delete your db folder and restart Petio. If this persists after the patch / steps above please re-open this issue
