### ISSUE TITLE
Users able to report episodes / movies they don't have in the library

### ISSUE THREAD

**Issue by brettpetch** [petio-team/petio#265]
**Is your feature request related to a problem? Please describe.**
Users are able to report things not currently in the collection.

**Describe the solution you'd like**
for the button to report being dependent on the ep/movie present in the library.

**Describe alternatives you've considered**
none.

**Additional context**
Confusing for admins to sift through.

**Comment by AshDyson** [comment]
We'll just match on if the show exists not the episode exists but other than that this is a good idea

**Comment by bakes82** [comment]
Why would you want to allow reports on episodes that a person doesnt have either?

**Comment by AshDyson** [comment]
Fixed in upcoming patch, report button only on shows / movies that are on server
