### ISSUE TITLE
Seperate Menus for reporting media / Improvements

### ISSUE THREAD

**Issue by brettpetch** [petio-team/petio#266]
**Is your feature request related to a problem? Please describe.**
Between movies and TV shows, these menus should be contextually different. 

**Describe the solution you'd like**
As an addition to this, the TV issues should have an episode / season option populated with episodes that have metadata / are present or something different. Movies might only have a few different issues, while a TV show may have an issue with a specific season, episode, or the whole show.

**Describe alternatives you've considered**
Having users type episode number / season number, otherwise marking as resolved.

**Additional context**
Makes harder than needs to be for admins to deal with issues.

**Comment by AshDyson** [comment]
I'm not entirely sure what you mean. We can add in proper episode / season info tagging to an issue which is planned but we don't have any plans to make the two menus "contextually different"?

**Comment by brettpetch** [comment]
It makes no sense for someone to “report a missing episode” for a movie, just a UX thing that could make reporting / issues a smoother experience.

**Comment by AshDyson** [comment]
> It makes no sense for someone to “report a missing episode” for a movie, just a UX thing that could make reporting / issues a smoother experience. 

Yeah you can't report a missing episode (unless there's a bug) for a movie. You get different options for movies or shows

**Comment by brettpetch** [comment]
Interesting... Seems like a bug of some kind... I'll do some further investigation later in the day.

**Comment by brettpetch** [comment]
I'll close this issue for the time being and see if I can get things sorted myself.
