### ISSUE TITLE
Ask for Sonarr's Language Profiles

### ISSUE THREAD

**Issue by jluis2k10** [petio-team/petio#268]
**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
As you may know, Sonarr has the possibility of setting the desired Language profile for a show, as opposed to Radarr where you set the desired language in the Quality profile itself.
Can you consider (if possible at all), to ask for the Language profile in Sonarr when approving a request or even setting a default one in the desired Sonarr server/using it in the filters?

**Describe alternatives you've considered**
Now i just have to edit the language profile in Sonarr once the show is approved, which is not really a hassle, but just asking.

**Additional context**
None

**Comment by AshDyson** [comment]
Yeah this makes sense. We're hoping to roll out a full i18n and translation update in phase 2 so this is definitely something to factor into this.

**Comment by AshDyson** [comment]
Closing this issue as its covered by #267
