### ISSUE TITLE
Path to no-poster.jpg and user-profile thumb image 404's when using base path

### ISSUE THREAD

**Issue by gilbN** [petio-team/petio#269]
**Describe the bug**
Path to `no-poster.jpg`, `no-poster-person.jpg`and user-profile thumb image 404's when using base path

*To Reproduce**
1. add a base path

**Expected behavior**
no 404 :P

**Screenshots**

![](https://selfhosted.app/f3c10/bUXASEka63.png/raw)

**Desktop (please complete the following information):**
 - OS: docker
 - Browser chrome

**Comment by angrycuban13** [comment]
@AshDyson is this a duplicate of #243 or this is different?

**Comment by gilbN** [comment]
Lol I even looked for a similar issue..🤦‍♂️

**Comment by AshDyson** [comment]
It's the same cause but different bug. Worth having both open

**Comment by angrycuban13** [comment]
> Lol I even looked for a similar issue..🤦‍♂️ I did make it at 4AM though...

I was just making sure. You know I love you 😘

**Comment by AshDyson** [comment]
Fix coming in next patch, fix referenced in #243
