### ISSUE TITLE
Radarr does not load upon adding it.

### ISSUE THREAD

**Issue by jahknem** [petio-team/petio#271]
**Describe the bug**
When adding radarr to petio  it does not load profiles or paths. As such the radarr instance cannot be activated in petio. It does however load movies which have already been added to petio. 

**To Reproduce**
1. Go to Settings -> Radarr
2. Click on Edit/Add new, add ip, port and api key. Click on test, see that test ist successfull
3. Scroll down to profile and path
4. See error that it keeps loading

**Expected behavior**
I expected the profile and the path to be choosable

**Screenshots**
![Bildschirmfoto vom 2021-03-20 14-07-192](https://user-images.githubusercontent.com/33702431/111870936-cdb95e80-8987-11eb-9ff0-6a8185906b27.png)

**Desktop (please complete the following information):**
 - OS: Manjaro
 - Browser Firefox
 - Version 86.0.1

**Additional context**
petio is in a different subnet from the radarr instance. All ipv4 communication from petio to radarr is allowed. Communication otherwise is prohibited. This is the same with sonarr, where it works fine

**Comment by angrycuban13** [comment]
Do you see anything in the logs?

**Comment by AshDyson** [comment]
What version of Radarr are you running? We only support v3

**Comment by jahknem** [comment]
> What version of Radarr are you running? We only support v3

That was it. Upgrading to V3 was a pain in the butt, but it does work now. Thanks!
