### ISSUE TITLE
Create separate repository for the Petio helm chart

### ISSUE THREAD

**Issue by onedr0p** [petio-team/petio#272]
**Is your feature request related to a problem? Please describe.**

With discussion in the discord server we have concluded it would be best to maintain the Petio helm chart in a separate git repository.

**Describe the solution you'd like**

For the maintainers to set up a new git repository called `petio-charts` and initialize it so we can open PRs.

**Additional context**

Discussion starts here

https://discord.com/channels/722180802871427104/822479309729169429/822572648835055616

**Comment by AshDyson** [comment]
Yeah I'm happy for this to get setup and anything required from me let me know. It's not something I'll be actively involved in as my skills align more with the main src maintenance.

**Comment by onedr0p** [comment]
For sure! Only action I can see is setting up the DNS record for the https://charts.petio.tv to point to a github pages branch once we get the helm chart added.

**Comment by AshDyson** [comment]
> For sure! Only action I can see is setting up the DNS record for the https://charts.petio.tv to point to a github pages branch once we get the helm chart added.

Yeah cool, just let me know when this needs to happen and I'll implement it. For now I'm going to close this FR as it's outside of anything we as a team are actively working on, but feel free to re-open as and when you need any input from me :)

**Comment by onedr0p** [comment]
Sorry my request is to create a `petio-charts` repo in `petio-team` org. Thanks!

**Comment by AshDyson** [comment]
Sorry haha, repo made and perms given to write to it!

**Comment by onedr0p** [comment]
Thanks!
