### ISSUE TITLE
Username/Email is Case-Sensitive at Login; Problem for Mobile Users

### ISSUE THREAD

**Issue by Hossy** [petio-team/petio#275]
**Describe the bug**
When trying to login, some mobile devices with automatically capitalize the first letter and cause a login failure because the match for username/email is case-sensitive.

**To Reproduce**
1. Login with an email address with a capital letter (as long as it doesn't show capital in the Users admin page)
2. Error: User not found

**Expected behavior**
Username/email match should be case-insensitive.

**Comment by AshDyson** [comment]
Addressed in upcoming patch, reopen if not complete
