### ISSUE TITLE
Request cards have a mis-aligned progress status element

### ISSUE THREAD

**Issue by ADRFranklin** [petio-team/petio#277]
**Describe the bug**
Request cards have their progress status mis-aligned as it's being adjusted based on the title content's size. 

**To Reproduce**
Request content with both small and long titles and you'll see the progress status in different places

**Expected behavior**
The request progress status should be correctly aligned throughout the cards and regardless of the title length

**Screenshots**
https://i.imgur.com/vuPyEy5.png

**Desktop (please complete the following information):**
 - OS: [e.g. iOS] Windows 10
 - Browser [e.g. chrome, safari] Brave
 - Version [e.g. 22] 1.21.77

**Additional context**
None

**Comment by AshDyson** [comment]
Fixed in upcoming patch
