### ISSUE TITLE
year match in filter

### ISSUE THREAD

**Issue by JoshHurn** [petio-team/petio#292]
**Describe the bug**
Year matching appears not to work and was defaulting to the user profile for TV shows only

**To Reproduce**
1. add a year filter under the TV shows filters.
2. Request a show 
3. If it doesnt match any other filters E.g. keyword, genre etc. then it won't be caught by year and will go to the user profile

**Expected behavior**
The filter should catch the year and send it to the correct sonarr instance

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Microsoft Edge
 - Version: Latest version

**Comment by AshDyson** [comment]
Issue fixed in upcoming patch
