### ISSUE TITLE
Admin can't log in when fast login is selected

### ISSUE THREAD

**Issue by jkirkcaldy** [petio-team/petio#293]
**Describe the bug**
Setting login to fast login and the admin user can't log in. Get a user not found error, setting the login mode back to '1' in the config.json returns the ability to login.

**To Reproduce**
1. Install on unriad using official Petio container and MongoDB container
2. set up as normal
3. enable fast login
4. try log in as admin

**Expected behavior**
To be able to login to the admin account

**Desktop (please complete the following information):**
 - OS: Unraid 6.9.1 Docker
 - Image Version 0.4.2-alpha

**Comment by AshDyson** [comment]
Are you sure this is in fact related to fast login and not db permissions? I cannot replicate this

**Comment by jkirkcaldy** [comment]
Yes, it's a database permissions issue. 

Thanks
