### ISSUE TITLE
User Thumbnails don't work with base url set

### ISSUE THREAD

**Issue by jkirkcaldy** [petio-team/petio#294]
**Describe the bug**
Base URL is missing in user thumbnails.
404 error on the thumbnail image. Base URL is missing from thumbnail URL. 
thumbnail should be https://domain.example.com/petio/api/user/thumb/$somestring
but it loads as https://domain.example.com/api/user/thumb/$somestring

**To Reproduce**
1. Set base URL to /petio 

**Expected behavior**
User thumbnails load

**Comment by angrycuban13** [comment]
This was addressed in 3e54c8d and will be rolled out to latest.
