### ISSUE TITLE
Request stuck at "No Status" when movie is already downloaded and in plex

### ISSUE THREAD

**Issue by jhabers** [petio-team/petio#309]
"Summerland" was requested by a user, it was downloaded and added to plex. Radarr connection in petio was removed and re-added. Now the status of "summerland" request in Petio admin shows "No Status". 

Here is my export of requests

https://pastebin.com/4syVp1yM

**Comment by AshDyson** [comment]
So just had a look through the code to confirm if this should be working. Here's what should happen:

Every night at 00:00 the library scan will run and update your Petio library, once it finishes it "checks old requests" and if it matches a movie in your Petio db (which is should) it will archive the request.

So something is definitely going wrong. Can you look for this message in your logs anywhere - "LIB CRON: Found missed request" this indicates a request has been found stalled and archived.

If possible if you can get compass installed and try and find "Summerland" in your movies collection within the Petio db and we can check everything matches up. You can use the query: `{title: "Summerland"}` to find it.

**Comment by AshDyson** [comment]
I think we fixed this in discord, error was caused from the Radarr server being removed. Feel free to re-open if this happens again
