### ISSUE TITLE
When logging in for the first time, petio crashes

### ISSUE THREAD

**Issue by evulhotdog** [petio-team/petio#316]
**Describe the bug**
I complete the app setup, then am prompted to log in for the first time. I then see that petio container crashes with exit code 1 with a TypeError exception. 

**To Reproduce**
1. I complete the app setup, then am prompted to log in for the first time. 
2. I log into the app with the newly created admin password.
3. I then see that petio container crashes with exit code 1 with a TypeError error. 

**Expected behavior**
I log in and the page loads

**Desktop (please complete the following information):**
 - OS: Docker

**Additional context**
Logs:
```
petio          | 2021-03-28 20:42:28 info: LOGIN: New login attempted
petio          | 2021-03-28 20:42:28 info: LOGIN: Request IP: ::ffff:127.0.0.1
petio          | 2021-03-28 20:42:28 info: LOGIN: No JWT: <REDACTED_EMAIL>
petio          | 2021-03-28 20:42:28 info: LOGIN: Request User: <REDACTED_EMAIL>
petio          | 2021-03-28 20:42:28 info: History returned from source
petio          | 2021-03-28 20:42:28 info: History returned from source
petio          | (node:8) UnhandledPromiseRejectionWarning: Error: getaddrinfo ENOTFOUND api.themoviedb.org
petio          |     at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:67:26)
petio          | (node:8) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 3)
petio          | (node:8) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'results' of undefined
petio          |     at trending (/app/api/tmdb/trending.js:28:30)
petio          |     at processTicksAndRejections (internal/process/task_queues.js:93:5)
petio          | (node:8) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 4)
petio          | 2021-03-28 20:42:28 error: TypeError: Cannot set property 'timestamp' of null
petio exited with code 1
```

**Comment by HalianElf** [comment]
You're having DNS issues. It can't resolve `api.themoviedb.org`

**Comment by evulhotdog** [comment]
You sure?

![image](https://user-images.githubusercontent.com/365456/112774961-59c32a00-9009-11eb-9894-c197ee278a28.png)

**Comment by angrycuban13** [comment]
> You sure?

Yes she is sure, the error below clearly shows issues with your container trying to reach that address.

```bash
 (node:8) UnhandledPromiseRejectionWarning: Error: getaddrinfo ENOTFOUND api.themoviedb.org
```

What installation method are you using?

**Comment by evulhotdog** [comment]
Docker on Ubuntu 20.04

**Comment by angrycuban13** [comment]
Do you have any custom docker networking doing IPV6?

**Comment by angrycuban13** [comment]
We had someone with a similar issue on [Discord](https://discord.com/channels/722180802871427104/729911436805144586/824309195591254037) and that was his solution.

Try that and let us know.

**Comment by angrycuban13** [comment]
Issue resolved on [Discord](https://discord.com/channels/722180802871427104/729911436805144586/825917900133105704).

Not a Petio issue but rather a configuration issue.
