### ISSUE TITLE
Admin requests - Series not linking correctly

### ISSUE THREAD

**Issue by annihilatethee** [petio-team/petio#319]
**Describe the bug**
Series on Admin Requests page not linking correctly

**To Reproduce**
1. Go to Admin Panel > Requests
2. Click on a Requested Series Title
3. Get "Not found - This page doesn't exist"

**Expected behavior**
The request page link is populated as /#/tv/XXXXX and the actual page it should be linking to is /#/series/XXXXX

**Comment by AshDyson** [comment]
Should be fixed in 0.4.4 re-open if not fixed when live
