### ISSUE TITLE
FR: Show requests a user has made in their profile area

### ISSUE THREAD

**Issue by ADRFranklin** [petio-team/petio#328]
**Is your feature request related to a problem? Please describe.**
Show a list of requests a user had made and have it displayed in their user area.

**Describe the solution you'd like**
Requests should already been stored with a link to the user that made it, so it's just searching the database for requests by a certain user and then displaying it

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by AshDyson** [comment]
Completed requests are still stored in the archive so we can output them quite easily
