### ISSUE TITLE
Requests not set to default Radarr profile (manual approval)

### ISSUE THREAD

**Issue by pandemiccum** [petio-team/petio#331]
Hi.

I added a Radarr profile with the initial Petio release. I updated to 0.4-4-alpha and let users give it a try. 

Requests are added, but when i go to "edit" the request itself does not adhere to my default radarr profile settings.

if i set and process request manually it works (but requires a lot of clicking if you have many requests)

**Expected behavior**
_Not_ having to set default server/profile/root folder for every request that needs manual approval

**Desktop (please complete the following information):**
 - Win Server 2016
 - Chrome 89

**Default Radarr profile**
![petio](https://user-images.githubusercontent.com/25054319/113345878-64e0c780-9333-11eb-86e3-d21960c26192.PNG)

**Request does not adhere to above settings**
![default](https://user-images.githubusercontent.com/25054319/113345821-47abf900-9333-11eb-92b6-498e6a23cbfa.PNG)

**Comment by AshDyson** [comment]
Can you confirm this bug persists in the latest release, it should have been fixed now, please re-open if it persists
