### ISSUE TITLE
Change admin email recepient

### ISSUE THREAD

**Issue by thunderstorm654** [petio-team/petio#333]
It would be cool to be able to change the designated admin or add a new one and not send emails to the original one. E.g. use case where admin who will manage Petio is not the same as the Plex admin. I see can add "moderators" but admin will still get emails. Bit of a unusual case I know but thought I'd ask anyway! Thanks for the great work already!

**Comment by AshDyson** [comment]
Petio is built around a single admin user which is the server owner so another admin cannot be added. We currently bcc the admin into every email just as a debugging tool whilst still in alpha but this will be changed soon. 

My recommendation would be to make the user you wish to control Petio to be a moderator so they have admin permissions and then once we have upgraded the notification system you will be able to specify who gets notified via email.

**Comment by thunderstorm654** [comment]
Thanks that makes sense, the ability to specify who gets the emails e.g. specific mods or whatever will be fine. For now, I temporarily changed the 'admin's' email :)
