### ISSUE TITLE
Can't edit Radarr/Sonarr config

### ISSUE THREAD

**Issue by Sebclem** [petio-team/petio#336]
**Describe the bug**
After clicking on `test` when adding a Sonarr or Radarr config, I got just the background and everything else is gone.
If I refresh, i can see that the config has been added, but if i click on `edit` -> Only background.
If I click on test, i got `Radarr Test Connection success!`
I got this error in the Chrome dev console: 
```
TypeError: this.state.profiles.map is not a function
    at s.value (radarr.js:406)
    at Va (react-dom.production.min.js:182)
    at Ba (react-dom.production.min.js:181)
    at Ou (react-dom.production.min.js:263)
    at mc (react-dom.production.min.js:246)
    at yc (react-dom.production.min.js:246)
    at uc (react-dom.production.min.js:239)
    at react-dom.production.min.js:123
    at t.unstable_runWithPriority (scheduler.production.min.js:19)
    at Go (react-dom.production.min.js:122)
```

**To Reproduce**
1. Try to add a Sonarr or Radarr server
2. Click on test => Only background
3. `F5`
4. Click on the newly added server edit button

**Expected behavior**

**Screenshots**
![image](https://user-images.githubusercontent.com/23737709/113475307-23f0cc00-9475-11eb-939f-7d6c141e08df.png)
![image](https://user-images.githubusercontent.com/23737709/113475323-3965f600-9475-11eb-99be-734417a7e0f0.png)

**Desktop (please complete the following information):**
 - OS: Windows 10 / Kubuntu 20.01
 - Browser: Chrome 89.0.4389.114
 - Version: 0.4.5-alpha (Docker)

**Comment by AshDyson** [comment]
Can you double check version, 0.4.5 aimed to fix this bug

**Comment by Sebclem** [comment]
This is my first install, so no cache or something, and Petio is up to date :
![image](https://user-images.githubusercontent.com/23737709/113480443-7e4d5500-9494-11eb-83b3-839575b47084.png)
![image](https://user-images.githubusercontent.com/23737709/113480335-21ea3580-9494-11eb-9524-99c8e8534a12.png)

I'm getting this in server logs, i don't know if it's related :
![image](https://user-images.githubusercontent.com/23737709/113480395-4cd48980-9494-11eb-95e9-0f9f36b0a57b.png)

**Comment by AshDyson** [comment]
Ok interesting. What version of RAdarr too?

**Comment by Sebclem** [comment]
Radarr: 3.1.0.4799
Sonarr: 3.0.6.1196

**Comment by AshDyson** [comment]
Attempted to replicate but unable to replicate, can you provide details about your Radarr config? Do you have paths / profiles setup etc?

**Comment by AshDyson** [comment]
After a code review it appears this issue can only be caused by a malformed Radarr response, this is not a bug but discuss this with us on Discord to help you fix whatever issue is causing this.

**Comment by nipuna-perera** [comment]
I am still seeing this on 0.4.5-alpha. Please re-open

**Comment by angrycuban13** [comment]
> I am still seeing this on 0.4.5-alpha. Please re-open

This isn't a bug or an issue. Make sure you're filling out the fields correctly. Feel free to join Discord if you need further assistance.
