### ISSUE TITLE
Add thumbnail option to discord embed.

### ISSUE THREAD

**Issue by davidjmorin** [petio-team/petio#340]
Would love to see the ability to have a thumbnail instead of the poster in discord notifications. 

![image](https://user-images.githubusercontent.com/9400895/113642249-60772000-964d-11eb-9763-6cd796eeb5db.png)

**Comment by ADRFranklin** [comment]
I feel this can be done, seems like a simple addition. This will probably be added in the next update if the team or I get around to doing it (probably me though).

**Comment by AshDyson** [comment]
This was included in 0.5.1 I believe
