### ISSUE TITLE
Custom Donation Button/option

### ISSUE THREAD

**Issue by morpheus2n2** [petio-team/petio#345]
It would be nice to have a Donation Button/Option with in the app to allow users to donate :D

**Comment by ADRFranklin** [comment]
Ash has stated before that he prefers people donate to charity rather then this project, so feel free to donate to charity in our cause and tell us about it in discord/reddit.

**Comment by morpheus2n2** [comment]
I actually was talking about one for users to donate tonus the Plex admin, so would like this reopened for that purpose.

**Comment by ADRFranklin** [comment]
That is not something Petio should be responsible for really. I mean it doesn't serve the goal of Petio in anyway and I think if you had your own discord server or something, that would be the best way to promote this kind of option.

**Comment by morpheus2n2** [comment]
Ok np
