### ISSUE TITLE
Add Sickrage/Medusa Support

### ISSUE THREAD

**Issue by Nelinski** [petio-team/petio#347]
**Request**
Add support for Sickrage + forks (Medusa) etc.

**Notes**
I saw a post on Discord saying there are no immediate plans to add support for Sickrage + forks as most users use *arr releases. Adding this for visibility of others as it's something I'd love in a future release.

**Comment by ADRFranklin** [comment]
This would require a huge re-write of our systems just to support these services, and I don't think the majority of people use Sickrage/Medusa when there is Sonarr/Radarr which are far more popular and heavily development.
