### ISSUE TITLE
Admin requests page crashes due to an uncaught exp

### ISSUE THREAD

**Issue by Orbsa** [petio-team/petio#353]
When loading the requests page on my server, It crashes to a blank page everytime. Debugging shows an error
`TypeError: Cannot read property 'seasonNumber' of undefined`

Not sure how to replicate. The show it is crashing on seems on par with the TVdb standard

**Screenshot**
![image](https://user-images.githubusercontent.com/9121811/114664014-5e9a0600-9cb8-11eb-9e8e-d738d2613b07.png)

**Comment by ADRFranklin** [comment]
Please follow the bug report format when reporting issues. I will close this, and let you re-make it with the correct format.
