### ISSUE TITLE
Stealth mode - Hide what this app is until you login to it.

### ISSUE THREAD

**Issue by beyondmeat** [petio-team/petio#377]
I rather not have a public facing site that makes it obvious what this app does...

So I want the ability to hide any references to 'Petio' on the login/auth screen. I also want to disable any media backdrop images on the login screen. Basically if you go to my petio url and you aren't logged in, you would have no idea the app is petio and it's for requesting media...

**Comment by angrycuban13** [comment]
Customization is planned down the road.

**Comment by AshDyson** [comment]
Yes this will be addressed with customisation of the logo / meta title. As for media backdrops, we don't use media backdrops. Closing this issue as it is addressed in the planned customisation coming in later versions
