### ISSUE TITLE
FR: Retro active scanning

### ISSUE THREAD

**Issue by akamel001** [petio-team/petio#378]
**Is your feature request related to a problem? Please describe.**
I deleted several movies from Radar / Plex as I thought I no longer wanted them. It was a lot of movies. It turned out I was wrong and someone else wanted them. So I go back into Petio to re-request the deleted movies but it shows as the movie is already available in Plex and I can not request it. 

**Describe the solution you'd like**
When a movie gets deleted from plex, reset its status in Petio so it can be re-requested. 

**Describe alternatives you've considered**
Allow manual override of movie status in Petio so we can at least re-request them if we wanted to. Or add an option to re-request.

**Comment by AshDyson** [comment]
As discussed on Discord this a FR for retro active scanning, will update the title accordingly

**Comment by akamel001** [comment]
Woohoo! Thanks!
