### ISSUE TITLE
Plex Library not importing into new instance

### ISSUE THREAD

**Issue by kennyparsons** [petio-team/petio#421]
**Describe the bug**
I have a brand new instance up (docker), connected to plex, radarr, and sonarr. However, it shows movies and TV shows that I DO have in my plex library as available to request. I expected it to show the green arrow in the top right. Instead, users are requesting movies that I already have. 
In the logs, I'm getting a lot of:
![image](https://user-images.githubusercontent.com/5930491/118902795-00c29480-b8dc-11eb-84bd-788b1a71cf5f.png)

and the corresponding requested movie:
![image](https://user-images.githubusercontent.com/5930491/118902805-06b87580-b8dc-11eb-9f21-e1c48f3142b7.png)

But the movie is in plex.

There are no failure to connect messages in the logs, or in testing the connection. And some shows/movies are getting nabbed so the connection is working. 

Also, I'm noticing some failures and then the next message is a successful meta data scan. But the movie still doesn't show up as available in plex when I search for it in Petio. It still shows as request-able.

Lastly, I'm noticing the partial scans (whether warn or info type messages) are only a small subset of my media library. A large portion of my media isn't being scanned, it appears. The same content reappears in the partial scan every 30 minutes.

**To Reproduce**
1. Setup brand new instance
2. connect plex
3. Existing TV Shows and Movies (some but not all) are not "imported" and show as requestable. 

**Expected behavior**
I would expect Petio to know I already have the movie and not let a user request it. If it is requested, though, it should not be stuck at "Downloaded" when it is already in plex. 

**Desktop (please complete the following information):**
 - OS: Mac, linux, and windows
 - Browser Chrome, Firefox, and Safari

**Comment by AshDyson** [comment]
Can't replicate so it's definitely something specific to likely the meta agent / matching here. Can you provide the XML for this movie in plex?
