### ISSUE TITLE
Proper handling of "Downloaded" requests

### ISSUE THREAD

**Issue by architdate** [petio-team/petio#426]
**Is your feature request related to a problem? Please describe.**
Petio currently cannot handle different meta-agents. Because of this, once a show is downloaded, it gets stuck in the admin request queue with the downloaded tag and is not cleared by the cronjob since it does not recognize that it has been processed by plex (through a different agent)

**Describe the solution you'd like**
A setting in the admin tab that makes petio delete the requests once they are marked as "Downloaded" and trigger all notification handlers (discord/email etc)

**Describe alternatives you've considered**
Adding support for other metadata agents (but this wont be feasible if there are changes in default behaviors anyway)

**Additional context**
![image](https://user-images.githubusercontent.com/17220860/119570572-e3615f00-bde2-11eb-86d8-cab3eaa64e4f.png)
All of these shows exist on my plex for several days

**Comment by waisenflix** [comment]
Same here.

[Status can't be edited](https://i.imgur.com/w72bbpj.png?1)

**Comment by tatzu** [comment]
Same problem for me with movies tvs-hows still finalizes when the are in plex but movies stays as downloaded even when the are in plex, dosent help to rematch them against tmdb.  Problem started about 2 weeks ago worked good before.

**Comment by AshDyson** [comment]
Status can now manually be set to "complete" which will trigger the usual event chain and archive the request. There is a limit with this though as Petio will still not actually see the movie / show so can't report that it is "available" in the frontend unless petio can match what is in plex to tmdb. It's kind of a half fix for now
