### ISSUE TITLE
trailer not working [bug]

### ISSUE THREAD

**Issue by n0pe0n** [petio-team/petio#454]
**Describe the bug**
trailer not working

**To Reproduce**
1. Setup brand new instance
2. open a trailer
3. don't load, it just goes blank

**Expected behavior**
I hope the trailers work correctly again

**Screenshots**

**Desktop (please complete the following information):**
 - OS: ubuntu 18.04
 - Version 0.5.1

**Comment by ADRFranklin** [comment]
A fix is incoming for this.

**Comment by n0pe0n** [comment]
thanks buddy
