### ISSUE TITLE
TV Show request stuck at no status 

### ISSUE THREAD

**Issue by hbooo** [petio-team/petio#456]
**Describe the bug**
When I try to request the tv show Panic (2021), I have an error in the docker logs and request is added with the status "no status"

**To Reproduce**
1. Go to petio home page
2. Search for panic
3. Request the tvshow from listing or from tv show page
4. Request is added with no status

**Expected behavior**
Request should be added with the correct status

**Logs**
`(node:227) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'hostname' of undefined
at Sonarr.process (/app/api/services/sonarr.js:32:22)
at Sonarr.get (/app/api/services/sonarr.js:72:17)
at Sonarr.lookup (/app/api/services/sonarr.js:141:17)
at Sonarr.addShow (/app/api/services/sonarr.js:214:31)
at /app/api/requests/process.js:284:26
at Array.map (<anonymous>)
at processRequest.sendToDvr (/app/api/requests/process.js:281:37)
at runMicrotasks (<anonymous>)
at processTicksAndRejections (internal/process/task_queues.js:93:5)
(node:227) UnhandledPromiseRejectionWarning: Unhandled promise rejection. 
This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). 
To terminate the node process on unhandled promise rejection, use the CLI flag --unhandled-rejections=strict (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 6)`

**Desktop (please complete the following information):**
 - OS: [e.g. iOS] Unraid
 - Browser [e.g. chrome, safari] Brave
 - Version [e.g. 22] V1.25.70

**Additional context**
Sonarr Version 3.0.6.1262
Petio Version 0.5.1-alpha

**Comment by AshDyson** [comment]
Thanks for the bug report. We'll look into this. I think it is something specific to your Sonarr setup as I was able to request the show without error but will continue digging and find the issue

**Comment by kesm** [comment]
Thanks, let me know if you need more information.

**Comment by hbooo** [comment]
Thanks, let me know if you need more information

**Comment by hbooo** [comment]
More info, I have this error in Sonarr : 
![image](https://user-images.githubusercontent.com/242125/123525742-3aed3600-d6d3-11eb-8365-8a432bcd8d9d.png)
and Profiles page in sonarr looks like this : 
![image](https://user-images.githubusercontent.com/242125/123525898-60c70a80-d6d4-11eb-94bc-357a849758e9.png)

**Comment by ADRFranklin** [comment]
I'm looking into this issue right now, I've also started experiencing it locally.

**Comment by ADRFranklin** [comment]
@hbooo Could you try something for me? Could you tell me if you have any custom user profiles, are they set for your user and can you try deleting them and re-creating them, and then try send a request.

**Comment by hbooo** [comment]
Sorry for the late answer, I only have default user profile in Petio

**Comment by hbooo** [comment]
Tried with a new profile in Petio (with auto approved) but still the same error in sonarr logs : 
`[Warn] SonarrErrorPipeline: Invalid request Validation failed:

-- LanguageProfileId: Language profile does not exist`

**Comment by hbooo** [comment]
Did a reinstall of Sonarr and now everything works fine. I think something went wrong when I upgraded from v2 to v3
