### ISSUE TITLE
Mismatched Calendar entries

### ISSUE THREAD

**Issue by architdate** [petio-team/petio#488]
**Describe the bug**
The calendar on petio does not match that of sonarr. The episode numbers match but not the show title

**To Reproduce**
1. Compare sonarr calenadar to petio calandar

**Expected behavior**
Both of them should match

**Screenshots**
![image](https://user-images.githubusercontent.com/17220860/124944629-0f0d7100-e040-11eb-95b4-4f9c602a9276.png)
![image](https://user-images.githubusercontent.com/17220860/124944642-12a0f800-e040-11eb-9fd0-673f8447e219.png)

**Desktop (please complete the following information):**
 - OS: Windows
 - Using binary

**Additional context**

**Comment by proteus077** [comment]
Having the same issue, running 0.5.2

**Comment by ADRFranklin** [comment]
@architdate @proteus077 Could you guys use the latest dev version as I just made a recent commit to fix this issue, could you guys take a look?

**Comment by proteus077** [comment]
@ADRFranklin seems to have the correct show names now, only thing I've now noticed is that the calendar in Petio is showing TV shows that are set as unmonitored in Sonarr, whereas the Sonarr calendar hides these shows. Not really a big deal and probably unrelated to this issue but worth mentioning. Thanks for fixing this up!

**Comment by ADRFranklin** [comment]
Good to know it works, but showing unmonitored shows is intentional.
