### ISSUE TITLE
Bazarr Integration

### ISSUE THREAD

**Issue by jeffreymooiweer** [petio-team/petio#496]
Is it possible to integrate Bazarr so that admins/users can easily update/search subtitles.

**Comment by angrycuban13** [comment]
That is outside the scope of Petio, but @AshDyson can weigh in.

**Comment by jeffreymooiweer** [comment]
Yeah I can relate to that. It would be nice if a user reported an sub issue I can solve it in the same application though.

**Comment by ADRFranklin** [comment]
I mean the user can already just report an issue with the sub already using the report feature. 

As for the integration of Bazarr, that won't be happening, this is like what angrycuban said, out of scope of Petio.
