### ISSUE TITLE
Requests being instantly removed after approving on both Radarr and Sonarr

### ISSUE THREAD

**Issue by mkono87** [petio-team/petio#504]
I am noticing that when I approve a movie or a tv show and refresh the page, it is instantly removed. I log is showing a 404. All the tests in settings are are passing so Im not sure exactly whats going on.

`2021-07-15 21:57:44 [32minfo[39m: REQ: The Tomorrow War removed from Radarr server - 4e125678-c735-4474-bca7-a3c5c98d862b
2021-07-15 21:57:44 [32minfo[39m: REQ: Request The Tomorrow War Archived!
2021-07-15 21:57:44 [33mwarn[39m: MAILER: Email disabled, skipping sending emails
(node:228) UnhandledPromiseRejectionWarning: Error: Request failed with status code 404
at createError (/app/api/node_modules/axios/lib/core/createError.js:16:15)
at settle (/app/api/node_modules/axios/lib/core/settle.js:17:12)
at IncomingMessage.handleStreamEnd (/app/api/node_modules/axios/lib/adapters/http.js:260:11)
at IncomingMessage.emit (events.js:387:35)
at endReadableNT (internal/streams/readable.js:1317:12)
at processTicksAndRejections (internal/process/task_queues.js:82:21)
(node:228) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 20)`

**Comment by pspuri91** [comment]
Has anybody picked up on this bug yet? I'm facing the same issue.

**Comment by beyondmeat** [comment]
Is the request added to the radarr instance though?

Requests will only show up if they are still pending or if the item is still unavailable. So if you request something and radarr downloads it, then that request will disappear as it's been fulfilled.

Maybe what you requested already exists? Like you at a movie to radarr, radarr scans the movie folder before searching and it found the movie already on disk. Then petio sees it as available in radarr and removes the request.

**Comment by AshDyson** [comment]
I'm not able to replicate this so it sounds like an issue with the connection to Radarr perhaps, speak to our support team on Discord and we can help you diagnose and fix whatever the issue is.
