### ISSUE TITLE
LanguageProfileId error when adding a new show 

### ISSUE THREAD

**Issue by Haldir31** [petio-team/petio#516]
**Describe the bug**
Unable to add a series in Sonarr. 3.0.6.1278. In logs, i have the following message:
error: SERVICE - SONARR: [Sonarr] Unable to add series
error: Error: Request failed with status code 400

On Sonarr side, i have the following message: Invalid request Validation failed:  -- LanguageProfileId: Language profile does not exist

**To Reproduce**
1. Using the default admin account, go to TV Shows
2. Click on a Shows like "Chucky (2021)"
3. Click on "Request Show"
4. The show is in Requests queue on Processing status with Status: No Status

**Expected behavior**
The show is added to Sonarr and will be downloaded, then imported and scanned to Plex. At the end, the show have to be "On Plex" status

**Desktop (please complete the following information):**
Fresh deployment, new docker containers
 - OS: Ubuntu 20.04 + Docker
 - Browser Edge Chromium
 - Version 0.5.2-alpha

**Comment by AshDyson** [comment]
Unable to replicate, do you have a language profile set in Sonarr? If you're still experiencing this issue please speak with our support team on Discord and we will try to diagnose and fix your problem.
