### ISSUE TITLE
Icons have off colors on either side

### ISSUE THREAD

**Issue by agneevX** [petio-team/petio#517]
**Describe the bug**

All icons/web assets have odd colors on either side, making it look weird. 

Noticeable on iOS A2HS.

![image](https://user-images.githubusercontent.com/19761269/127671111-8ddf957e-8fa6-4b55-add0-95aca71a37d2.png)

**Comment by AshDyson** [comment]
We will be providing new icons for PWA with the updated UI, thanks for flagging this, I'll make sure whatever generator I used doesn't do this next time.
