### ISSUE TITLE
editing an admin request throws error and broken app state (no ui elements)

### ISSUE THREAD

**Issue by beyondmeat** [petio-team/petio#518]
**Describe the bug**
Using admin panel, editing requests doesn't work and breaks the app, requiring a refresh to fix.

Docker: ghcr.io/petio-team/petio:preview (image is pulled nightly)
0.5.3-alpha

**To Reproduce**

1.  Have a user make a movie request that is (auto) approved
2. Open the added movie in radarr
3. Delete the movie in radarr (optional)
4. edit the request as admin
5. see blank screen, check dev console

**Expected behavior**
It works

**Screenshots**
n/a

**Desktop (please complete the following information):**
 - OS: Windows 11 Insider Dev Channel
 - Browser: Edge (same happens with Chrome)
 - Version 93.0.961.7 (Official build) dev (64-bit)

**Additional context**

```react-dom.production.min.js:123 Uncaught TypeError: Cannot read properties of undefined (reading 'path')
    at s.value (Requests.js:349)
    at Requests.js:576```

**Comment by ADRFranklin** [comment]
What version of Petio are you using?

**Comment by beyondmeat** [comment]
Docker: ghcr.io/petio-team/petio:preview (pulled today)
0.5.3-alpha

**Comment by beyondmeat** [comment]
fixed by using ghcr.io/petio-team/petio:dev
which updated to 0.5.4-alpha
