### ISSUE TITLE
Select between: "Normal request" and a "4K request" button

### ISSUE THREAD

**Issue by casperse** [petio-team/petio#589]
I have done the setup for HD and 4K and the filters to automate and it works great!
BUT - if a user have access to both - radarr HD + 4K then it will always be requested as having both resolutions
Not all movies are created equal LOL

Only solution so far have been to change the user profile, between each request

**Describe the solution you'd like**

Just create two request buttons for any user with a profile that have access to both 2x Radarr or 2x Sonarr HD + 4K

Request button 1: for HD only
Request button 2: for HD & 4K version

(Hide button 2 if there is only 1 instant of Radarr and Sonarr access in the user profile)
 
**Describe alternatives you've considered**

This request tool is so much better because I can automate where genres are placed
But other request tool can differentiate between HD and HD + 4K requests

**Comment by AshDyson** [comment]
This unfortunately goes against the core ideal of Petio, simplicity for end users. That's why we have the filter system. Asking a user to pick what resolution they want will cause more headache than it solves, so unfortunately for now this isn't goingto be included in Petio.
