### ISSUE TITLE
Missing Review section on the main page for all users to see?

### ISSUE THREAD

**Issue by casperse** [petio-team/petio#592]
If people spent the time making a review then it needs to be visible for other users (At least for the local group)
- And please add the possibility for the reviews to be without a user name

**Comment by AshDyson** [comment]
Reviews will factor in more in the future versions of Petio but for now they're only displayed on the media the review is for. Soon reviews will help shape the landing page to promote movies and tv that users have liked rather than a big list of recent reviews.

In summary this is already planned
