### ISSUE TITLE
At sporadic times of the week, libraries refuse to show available in Petio.

### ISSUE THREAD

**Issue by Xenocell12** [petio-team/petio#658]
**Describe the bug**
Some libraries, specifically TV shows refuse to show available. It appears that it doesn't even scan them when doing TMDB Show scans.

Some top level TV Show libraries show to be available.

**To Reproduce**
No known way to reproduce. Does this on a brand new install as well through Atlas DB, and local DB.

**Expected behavior**
Last week the libraries were showing available for sure, but then suddenly, TV shows showed no longer available, but showed requestable. 

**Screenshots**
N/A

**Desktop (please complete the following information):**
 - OS: Windows 10 x64 
 - Browser Chrome
 - Version: 96.0.4664.110

**Smartphone (please complete the following information):**
Same issue

**Additional context**

While bypassing all proxies and web hosts, etc. This issue is also present when browsing directly to localhost:7777

**Comment by AshDyson** [comment]
This sounds like perhaps an intermittent Plex connection issue. If Petio can't find certain media items when it scans then it will remove them from being "available". As this isn't a wider issue with Petio I'm going to close the issue and recommend you talk with our support team on Discord to better diagnose and hopefully resolve the issue.
