### ISSUE TITLE
The oh-so-famous iPhone notch...

### ISSUE THREAD

**Issue by marchershey** [petio-team/petio#665]
**Describe the bug**
The oh-so-famous iPhone notch causing issues with the admin panel on mobile.

**To Reproduce**
On any *notched* iPhone, open the browser, visit **/admin/#/requests** (or any page which has a table), check out the clipping.

**Expected behavior**
No clipping with correct padding.

**Screenshots**
![image](https://i.imgur.com/QaxZDJz.jpg)

**Smartphone (please complete the following information):**
 - Device: **iPhone X and above**
 - OS: ANY
 - Browser ANY
 - Version ANY

**Additional context**
[CSS_TRICKS](https://css-tricks.com/the-notch-and-css/) has an amazing guide on this and it includes the proper way to handle this. To solve this, simply add the following to the body (or the container, etc):

```css
padding: env(safe-area-inset-top) env(safe-area-inset-right) env(safe-area-inset-bottom) env(safe-area-inset-left);
```

PS: I did notice that you're using using `100% screen-height`, so this may be a little trickier for you. I remember I ran into a problem with it a while back. Can't remember the exact details. But that's it, just a heads up. 

*Edit: added screenshot*

**Comment by marchershey** [comment]
...or if you're into [overkilling](https://twitter.com/vojtastavik/status/907911237983449088). lol

**Comment by AshDyson** [comment]
Hi, I'm not able to replicate this on the page you mentioned. Here's a screenshot showing no clipping for me
![Simulator Screen Shot - iPhone 11 - 2022-01-06 at 14 20 22](https://user-images.githubusercontent.com/28293531/148397431-803a35ee-bb9e-4966-8c0f-0b57075a75e9.png)

**Comment by marchershey** [comment]
@AshDyson My apologies, I should have added that if you flip to landscape mode, your top notch should be blocking content. 

I haven't throughly checked anywhere else, but I'll keep a lookout. This issue really isn't that important, really. Just nit-picking because it's so damn perfect. lol 

My *artistic* illustration below hopefully explains this a little better. I didn't mean to have the menu open, but if I'm being honest, I didn't notice until after I edited & uploaded the image. lol

![image](https://i.imgur.com/QaxZDJz.jpg)

**Comment by angrycuban13** [comment]
I can confirm that the notch does mess up the UI.

**Comment by AshDyson** [comment]
Ok cool, I hadn't anticipated people using horizontal, we use the env padding techniques already but only on top bottom not on left right, will get this implemented for the new UI

**Comment by angrycuban13** [comment]
Screenshot for prosperity

![image](https://user-images.githubusercontent.com/39564898/148662892-889a5a43-a188-4afc-976c-4c6c8533d80d.jpeg)

**Comment by AshDyson** [comment]
Addressed in the new UI build.
