### ISSUE TITLE
Add visual indicator that content has already been requested

### ISSUE THREAD

**Issue by mvanbaak** [petio-team/petio#695]
**Describe the solution you'd like**
At the moment, available media has a green mark at the right upper corner of the poster.
It would be very nice if there would be some colored marker in that corner for media that has been requested by me or another user already.

As example, in the current webfrontend, this is what I see under 'Trending Movies'.
The new spider-man movie has been requested by some users already, and I (and others, I asked my users) would simply not click it if there was some indicator showing it was requested already. Now I do ;P

<img width="361" alt="ch23f2" src="https://user-images.githubusercontent.com/1928231/155758081-9b41aef5-330c-4df3-a7c2-021564dbb582.png">

**Comment by HalianElf** [comment]
This is in the new UI already.

**Comment by AshDyson** [comment]
The old UI actually already does this, there was a bug where the UI would sometimes cache requested status which is why you're probably not seeing it here. This is also fixed in the upcoming new UI build
