### ISSUE TITLE
'Users' page under admin settings not loading

### ISSUE THREAD

**Issue by es9o** [petio-team/petio#696]
**Describe the bug**
Upon navigating to it via the admin section, the 'Users' page appears in the browser for a split second and then goes blank.

**To Reproduce**
1. Navigate to Petio via web browser
2. Click 'Admin' from the menu
3. Click 'Users' from the menu
4. Notice that the page will briefly appear and then revert to a blank page.

**Expected behavior**
I should be able to see the list of my users.

**Screenshots**
I've attached a screenshot of the error I receive in the console when navigating to the 'Users' page.
![Petio Error](https://user-images.githubusercontent.com/24829058/156019459-6c479117-2325-4726-bdb0-97749c9b1d56.png)

**Desktop (please complete the following information):**
 - OS: Docker (Linux - Ubuntu 20.04)
 - Browser: Edge (Chromium)
 - Version:  98.0.1108.62

**Additional context**
I have tried disabling adblock to see if that was creating issues, but experienced the same results.

I'm also experiencing a similar issue with the Radarr and Sonarr settings pages as well. Everything else on the site works as expected.

**Comment by AshDyson** [comment]
Looks like you're getting 404 errors from the internal API, I would jump on discord support to help debug this

**Comment by AshDyson** [comment]
Confirmed reverse proxy issue in discord
