### ISSUE TITLE
Telegram Test fails

### ISSUE THREAD

**Issue by poiromaniax** [petio-team/petio#714]
**Describe the bug**
I am setting up Telegram for the first time.
I created a bot, added it to a group (with permissions to access messages)
Generated the access token and collected the chat ID

Clicking "Test" fails, and the log doesnt show more information

**Screenshots**
<img width="712" alt="image" src="https://user-images.githubusercontent.com/15910083/173548568-21e6a629-4db6-4b27-8bd4-d1e4b0cf800e.png">
<img width="380" alt="image" src="https://user-images.githubusercontent.com/15910083/173548629-d4d80090-60f5-4520-be78-d28d644b09c0.png">

![image](https://user-images.githubusercontent.com/15910083/173548403-bcb43bb4-a772-4fe6-bcf0-f556930cd4f6.png)

**Desktop (please complete the following information):**
 - OS: macOS
 - Browser Chrome

**Comment by angrycuban13** [comment]
Look at the browser console under the Network tab when you click "Test", click on the failed request and click on the "Response" tab. What is the error?

**Comment by poiromaniax** [comment]
I dont see any failed requests in he Network tab.
<img width="882" alt="image" src="https://user-images.githubusercontent.com/15910083/173675869-aca2326f-6c27-496b-bc05-244f528270af.png">

**Comment by poiromaniax** [comment]
Coming back to this to solve my own issue

Be sure to include the minus symbol in your Telegram Group ID. I just assumed that was a separator and left it out.

Added it in and now notifications work just fine :)
