### ISSUE TITLE
Cant Auth. Plex server (2FA) in Petio

### ISSUE THREAD

**Issue by casperse** [petio-team/petio#722]
**Describe the bug**
After the security breach at Plex announced today
I have reset my password and setup 2FA

FIRST Logging in to PETIO with Plex account and 2FA works fine!

**To Reproduce**

BUT the Plex connection does not provide the 2FA and I think this is why this doesnt work?
![image](https://user-images.githubusercontent.com/2026859/186376623-a76c486c-c1d2-4498-b3f5-67ab34eb1044.png)

**Comment by casperse** [comment]
Update: I solved this by opening the file config.json and manually pasting the correct token to the config
Everything works now (Still a bug :-)

**Comment by ADRFranklin** [comment]
When you login with the 3rd party auth, it generates a token. That token is not protected by any 2fa and is what Petio uses to access the plex tv api/plex api. 

I'm not sure without some console logs or server logs, what is going on for you. If you could provide more information that would help us to identify

**Comment by angrycuban13** [comment]
Looks like Plex auth was having some issues last night. This could be the cause

**Comment by josway** [comment]
I am having a similar issue. 

Logs are showing reason as Host is not in the cert's alt name.

**Comment by angrycuban13** [comment]
This is likely not a Petio issue but rather ongoing issues with Plex.

**Comment by MrMxyzptlk** [comment]
I'm having the same issues; Petio will not authenticate to Plex so I can't use it.

**Comment by angrycuban13** [comment]
> I'm having the same issues; Petio will not authenticate to Plex so I can't use it.

Your issue likely is the Plex address you selected when you initially went through your setup. You might need to re-do the initial config and make sure you select the correct one.
