### ISSUE TITLE
FR: Media info in email

### ISSUE THREAD

**Issue by poiromaniax** [petio-team/petio#733]
**Is your feature request related to a problem? Please describe.**
As an admin, I receive requests for media - many times I do not know what this media is. I do not have a way to simply find/link this info from the request email

**Describe the solution you'd like**
A synopsis of the media + rating, or a simple link to TMDB/IMDB/RottenTomatoes etc

**Comment by ADRFranklin** [comment]
This is already been addressed in development, the notification system has been rewritten to allow for better and more notification providers in the future.

**Comment by poiromaniax** [comment]
@ADRFranklin is there a timeline for the next release?

**Comment by ADRFranklin** [comment]
I'm hoping to get the next release out in the upcoming weeks.
